kreate:
  active: true
  ForbiddenLineComment:
    active: true
    allowedPattern: ''
  ForbiddenBlockComment:
    active: true
    licenseHeaderPattern: 'Copyright'
  ForbiddenElse:
    active: true
  ChainedCallLimit:
    active: true
    maxCalls: 2
  OneTopLevelTypePerFile:
    active: true
  KDocOnNonPublicDeclaration:
    active: true
    allowProtected: false
  KDocWithoutSinceTag:
    active: true
  SingleLineKDocWithBlockTag:
    active: true
  KDocClosingMarkerOnSharedLine:
    active: true
  KDocSeparatedFromDeclaration:
    active: true
