// The header is generated by the `kreateJniHeaders` task from the `external` declarations
// in the Kotlin sources. Including it means the C++ compiler checks these definitions
// against the names and signatures the JVM will actually look up, instead of leaving a
// typo to surface at runtime as an UnsatisfiedLinkError.
#include "example_jni.h"

JNIEXPORT jstring JNICALL Java_com_davils_example_JNI_hello(JNIEnv* env, jobject receiver) {
    return env->NewStringUTF("Hello from C++");
}
