/*
 * Copyright 2026 Davils
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.davils.kreate.module.platform.jvm.jni.tasks

import com.davils.kreate.jobs.Task
import com.davils.kreate.system.AARCH64_ID
import com.davils.kreate.system.X86_64_ID
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Generates the `KreateNativeLoader` object into the project's sources.
 *
 * A published JAR that merely contains a shared library is not usable on its own: the JVM
 * only resolves `System.loadLibrary` against `java.library.path`, which a consumer of the
 * artifact has no reason to set. The generated loader closes that gap by falling back to
 * extracting the packaged library from the classpath into a temporary directory.
 *
 * The loader is generated as source rather than shipped as a separate runtime artifact on
 * purpose. A separate artifact would have to be version-matched against the plugin by
 * every consumer, and would add a compile dependency to a project that currently needs
 * none.
 *
 * @since 2.0.0
 */
@CacheableTask
public abstract class GenerateNativeLoader : Task(
    "Generates the runtime loader for packaged native libraries.",
    "kreate jni"
) {
    /**
     * The package the loader is generated into.
     * @since 2.0.0
     */
    @get:Input
    public abstract val packageName: Property<String>

    /**
     * The resource directory inside the JAR the native libraries are packaged under.
     * @since 2.0.0
     */
    @get:Input
    public abstract val resourcePath: Property<String>

    /**
     * The coordinate the platform artifacts are published under, without the platform suffix,
     * for example `com.example:mylib:1.0.0`.
     *
     * Empty when the natives are bundled into the main JAR, in which case a missing library is
     * a build defect rather than a missing declaration and no coordinate would help.
     *
     * @since 2.2.0
     */
    @get:Input
    public abstract val artifactCoordinate: Property<String>

    /**
     * The platforms this version publishes a native artifact for.
     *
     * Empty when the natives are bundled into the main JAR.
     *
     * @since 2.2.0
     */
    @get:Input
    public abstract val publishedPlatforms: ListProperty<String>

    /**
     * The directory the generated source file is written to.
     * @since 2.0.0
     */
    @get:OutputDirectory
    public abstract val outputDirectory: DirectoryProperty

    /**
     * Writes the generated loader source file.
     *
     * @return Unit
     * @since 2.0.0
     */
    @TaskAction
    public fun execute() {
        val target = outputDirectory.get().asFile
            .resolve(packageName.get().replace('.', '/'))
        target.mkdirs()

        target.resolve("$LOADER_CLASS_NAME.kt").writeText(renderLoader())
    }

    /**
     * Renders the loader source.
     *
     * @return The generated Kotlin source file contents.
     * @since 2.0.0
     */
    private fun renderLoader(): String = buildString {
        appendLine("// This file is generated by Kreate. Do not edit — it is overwritten on every build.")
        appendLine()
        appendLine("package ${packageName.get()}")
        appendLine()
        appendLine("import java.nio.file.Files")
        appendLine("import java.nio.file.StandardCopyOption")
        appendLine()
        appendLine("/**")
        appendLine(" * Loads native libraries that were packaged into this artifact by Kreate.")
        appendLine(" *")
        appendLine(" * @since 2.0.0")
        appendLine(" */")
        appendLine("public object $LOADER_CLASS_NAME {")
        appendLine("    private val loaded = mutableSetOf<String>()")
        appendLine()
        append(renderLoadFunction())
        appendLine()
        append(renderHintFunction())
        appendLine()
        append(renderPlatformHelpers())
        appendLine("}")
    }

    /**
     * Renders the helper that turns a missing library into an actionable message.
     *
     * With the natives bundled into the main JAR a missing library is a defect in the library's
     * own build, and there is nothing useful to tell the consumer. With per-platform artifacts
     * the overwhelmingly likely cause is a dependency the consumer did not declare — so the
     * message names the exact coordinate, and lists the platforms this version actually shipped
     * so that "you forgot the dependency" is distinguishable from "this platform does not exist
     * for this version".
     *
     * @return The rendered function, indented for inclusion in the object body.
     * @since 2.2.0
     */
    private fun renderHintFunction(): String {
        val coordinate = artifactCoordinate.getOrElse("")
        val platforms = publishedPlatforms.getOrElse(emptyList())

        if (coordinate.isEmpty()) {
            return """
                |    private fun hint(): String = ""
                |
            """.trimMargin()
        }

        val (group, artifactAndVersion) = coordinate.split(':', limit = 2)
        val (artifact, version) = artifactAndVersion.split(':', limit = 2)
        val published = platforms.joinToString(", ")

        return """
            |    private fun hint(): String = "\n\n" +
            |        "Add the platform artifact to your runtime classpath:\n\n" +
            |        "    runtimeOnly(\"$group:$artifact-" + platformId() + ":$version\")\n\n" +
            |        "Platforms published with this version: $published"
            |
        """.trimMargin()
    }

    /**
     * Renders the public `load` function of the generated loader.
     *
     * @return The rendered function, indented for inclusion in the object body.
     * @since 2.0.0
     */
    private fun renderLoadFunction(): String = """
        |    /**
        |     * Loads the native library with the given base name.
        |     *
        |     * The library is first looked up the ordinary way, so a developer running with
        |     * `-Djava.library.path` set keeps using their locally built binary. Only when
        |     * that fails is the packaged copy extracted from the classpath and loaded from
        |     * a temporary directory.
        |     *
        |     * @param name The library base name, without prefix or file extension.
        |     * @return Unit
        |     * @throws UnsatisfiedLinkError If the library is neither on the library path
        |     *   nor packaged for the current platform.
        |     * @since 2.0.0
        |     */
        |    @Synchronized
        |    public fun load(name: String) {
        |        if (!loaded.add(name)) return
        |
        |        try {
        |            System.loadLibrary(name)
        |            return
        |        } catch (_: UnsatisfiedLinkError) {
        |            // Fall through to the packaged copy.
        |        }
        |
        |        val resource = "/${resourcePath.get()}/" + platformId() + "/" + fileName(name)
        |        val stream = $LOADER_CLASS_NAME::class.java.getResourceAsStream(resource)
        |            ?: run {
        |                loaded.remove(name)
        |                throw UnsatisfiedLinkError(
        |                    "Native library '" + name + "' is not on java.library.path and no " +
        |                        "packaged copy was found at " + resource + "." + hint()
        |                )
        |            }
        |
        |        val directory = Files.createTempDirectory("kreate-jni")
        |        val target = directory.resolve(fileName(name))
        |        stream.use { input ->
        |            Files.copy(input, target, StandardCopyOption.REPLACE_EXISTING)
        |        }
        |        target.toFile().deleteOnExit()
        |        directory.toFile().deleteOnExit()
        |
        |        System.load(target.toAbsolutePath().toString())
        |    }
        |
    """.trimMargin()

    /**
     * Renders the platform detection helpers of the generated loader.
     *
     * The logic is duplicated from Kreate's own platform helpers on purpose: the generated
     * code runs in the consumer's process, which must not need a dependency on the plugin. The
     * identifiers themselves are interpolated from [X86_64_ID] and [AARCH64_ID] rather than written
     * out again, so the packaging side and the loading side cannot drift.
     *
     * @return The rendered helpers, indented for inclusion in the object body.
     * @since 2.0.0
     */
    private fun renderPlatformHelpers(): String = """
        |    private fun platformId(): String {
        |        val osName = System.getProperty("os.name").lowercase()
        |        val osId = when {
        |            osName.contains("win") -> "windows"
        |            osName.contains("mac") || osName.contains("darwin") -> "macos"
        |            else -> "linux"
        |        }
        |
        |        val archName = System.getProperty("os.arch").lowercase()
        |        val archId = if (archName.contains("aarch64") || archName.contains("arm64")) {
        |            "$AARCH64_ID"
        |        } else {
        |            "$X86_64_ID"
        |        }
        |
        |        return osId + "-" + archId
        |    }
        |
        |    private fun fileName(name: String): String {
        |        val osName = System.getProperty("os.name").lowercase()
        |        return when {
        |            osName.contains("win") -> name + ".dll"
        |            osName.contains("mac") || osName.contains("darwin") -> "lib" + name + ".dylib"
        |            else -> "lib" + name + ".so"
        |        }
        |    }
        |
    """.trimMargin()

    /**
     * Companion object for [GenerateNativeLoader].
     *
     * @since 2.0.0
     */
    public companion object {
        /**
         * The name of the generated loader object.
         * @since 2.0.0
         */
        public const val LOADER_CLASS_NAME: String = "KreateNativeLoader"
    }
}
