/*
 * Copyright 2026 Davils
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.davils.kreate.jni.task

import com.davils.kreate.jni.signature.JniSignatures
import com.davils.kreate.jni.signature.NativeMethod
import com.davils.kreate.jni.signature.readNativeMethods
import com.davils.kreate.task.KreateTask
import com.davils.kreate.task.KreateTaskGroup
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.SkipWhenEmpty
import org.gradle.api.tasks.TaskAction
import java.io.File

private const val CLASS_FILE_PATTERN: String = "**/*.class"

private const val GUARD_REPLACEMENT: Char = '_'

@CacheableTask
internal abstract class GenerateJniHeaders : KreateTask(
    "Generates a JNI header from the native methods of the compiled classes.",
    KreateTaskGroup.JNI
) {
    @get:InputFiles
    @get:SkipWhenEmpty
    @get:PathSensitive(PathSensitivity.RELATIVE)
    public abstract val classDirectories: ConfigurableFileCollection

    @get:Input
    public abstract val headerFileName: Property<String>

    @get:OutputDirectory
    public abstract val outputDirectory: DirectoryProperty

    @TaskAction
    public fun execute() {
        val classFiles = classDirectories.asFileTree.matching { include(CLASS_FILE_PATTERN) }.files
        val methods = classFiles.sortedBy { it.absolutePath }
            .flatMap { classFile -> readNativeMethods(classFile.readBytes()) }

        val targetDirectory = outputDirectory.get().asFile
        targetDirectory.mkdirs()
        val header = targetDirectory.resolve(headerFileName.get())

        reportDeclarations(methods, header)
        header.writeText(renderHeader(methods))
    }

    private fun reportDeclarations(methods: List<NativeMethod>, header: File) {
        if (methods.isEmpty()) {
            logger.info("No native methods found; writing an empty JNI header to $header.")
            return
        }
        logger.lifecycle("Generated JNI declarations for ${methods.size} native method(s).")
    }

    private fun renderHeader(methods: List<NativeMethod>): String {
        val guard = includeGuard()
        val methodsByClass = methods.groupBy { it.ownerInternalName }.toSortedMap()

        return buildString {
            appendLine("/* This file is generated by Kreate. Do not edit — it is overwritten on every build. */")
            appendLine("#ifndef $guard")
            appendLine("#define $guard")
            appendLine()
            appendLine("#include <jni.h>")
            appendLine()
            appendLine("#ifdef __cplusplus")
            appendLine("extern \"C\" {")
            appendLine("#endif")
            appendLine()

            methodsByClass.values.forEach { classMethods -> appendDeclarations(classMethods) }

            appendLine("#ifdef __cplusplus")
            appendLine("}")
            appendLine("#endif")
            appendLine()
            append("#endif /* $guard */")
        }
    }

    private fun StringBuilder.appendDeclarations(classMethods: List<NativeMethod>) {
        JniSignatures.renderDeclarations(classMethods).forEach { declaration ->
            appendLine(declaration)
            appendLine()
        }
    }

    private fun includeGuard(): String {
        val upperCaseName = headerFileName.get().uppercase()
        return upperCaseName.map(::guardCharacter).joinToString("")
    }

    private fun guardCharacter(character: Char): Char {
        val isGuardSafe = character in 'A'..'Z' || character in '0'..'9'
        if (isGuardSafe) return character
        return GUARD_REPLACEMENT
    }
}
