/*
 * Copyright 2026 Davils
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.davils.kreate.jni.task

import com.davils.kreate.host.AARCH64_ID
import com.davils.kreate.host.X86_64_ID
import com.davils.kreate.task.KreateTask
import com.davils.kreate.task.KreateTaskGroup
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

private const val LOADER_CLASS_NAME: String = "KreateNativeLoader"

@CacheableTask
internal abstract class GenerateNativeLoader : KreateTask(
    "Generates the runtime loader for packaged native libraries.",
    KreateTaskGroup.JNI
) {
    @get:Input
    public abstract val packageName: Property<String>

    @get:Input
    public abstract val resourcePath: Property<String>

    @get:Input
    public abstract val artifactCoordinate: Property<String>

    @get:Input
    public abstract val publishedPlatforms: ListProperty<String>

    @get:OutputDirectory
    public abstract val outputDirectory: DirectoryProperty

    @TaskAction
    public fun execute() {
        val target = outputDirectory.get().asFile
            .resolve(packageName.get().replace('.', '/'))
        target.mkdirs()

        target.resolve("$LOADER_CLASS_NAME.kt").writeText(renderLoader())
    }

    private fun renderLoader(): String = buildString {
        appendLine("// This file is generated by Kreate. Do not edit — it is overwritten on every build.")
        appendLine()
        appendLine("package ${packageName.get()}")
        appendLine()
        appendLine("import java.nio.file.Files")
        appendLine("import java.nio.file.StandardCopyOption")
        appendLine()
        appendLine("/**")
        appendLine(" * Loads native libraries that were packaged into this artifact by Kreate.")
        appendLine(" *")
        appendLine(" * @since 2.0.0")
        appendLine(" */")
        appendLine("public object $LOADER_CLASS_NAME {")
        appendLine("    private val loaded = mutableSetOf<String>()")
        appendLine()
        append(renderLoadFunction())
        appendLine()
        append(renderHintFunction())
        appendLine()
        append(renderPlatformHelpers())
        appendLine("}")
    }

    private fun renderHintFunction(): String {
        val coordinate = artifactCoordinate.getOrElse("")
        val platforms = publishedPlatforms.getOrElse(emptyList())

        if (coordinate.isEmpty()) {
            return """
                |    private fun hint(): String = ""
                |
            """.trimMargin()
        }

        val (group, artifactAndVersion) = coordinate.split(':', limit = 2)
        val (artifact, version) = artifactAndVersion.split(':', limit = 2)
        val published = platforms.joinToString(", ")

        return """
            |    private fun hint(): String = "\n\n" +
            |        "Add the platform artifact to your runtime classpath:\n\n" +
            |        "    runtimeOnly(\"$group:$artifact-" + platformId() + ":$version\")\n\n" +
            |        "Platforms published with this version: $published"
            |
        """.trimMargin()
    }

    private fun renderLoadFunction(): String = """
        |    /**
        |     * Loads the native library with the given base name.
        |     *
        |     * The library is first looked up the ordinary way, so a developer running with
        |     * `-Djava.library.path` set keeps using their locally built binary. Only when
        |     * that fails is the packaged copy extracted from the classpath and loaded from
        |     * a temporary directory.
        |     *
        |     * @param name The library base name, without prefix or file extension.
        |     * @return Unit
        |     * @throws UnsatisfiedLinkError If the library is neither on the library path
        |     *   nor packaged for the current platform.
        |     * @since 2.0.0
        |     */
        |    @Synchronized
        |    public fun load(name: String) {
        |        if (!loaded.add(name)) return
        |
        |        try {
        |            System.loadLibrary(name)
        |            return
        |        } catch (_: UnsatisfiedLinkError) {
        |            // Fall through to the packaged copy.
        |        }
        |
        |        val resource = "/${resourcePath.get()}/" + platformId() + "/" + fileName(name)
        |        val stream = $LOADER_CLASS_NAME::class.java.getResourceAsStream(resource)
        |            ?: run {
        |                loaded.remove(name)
        |                throw UnsatisfiedLinkError(
        |                    "Native library '" + name + "' is not on java.library.path and no " +
        |                        "packaged copy was found at " + resource + "." + hint()
        |                )
        |            }
        |
        |        val directory = Files.createTempDirectory("kreate-jni")
        |        val target = directory.resolve(fileName(name))
        |        stream.use { input ->
        |            Files.copy(input, target, StandardCopyOption.REPLACE_EXISTING)
        |        }
        |        target.toFile().deleteOnExit()
        |        directory.toFile().deleteOnExit()
        |
        |        System.load(target.toAbsolutePath().toString())
        |    }
        |
    """.trimMargin()

    private fun renderPlatformHelpers(): String = """
        |    private fun platformId(): String {
        |        val osName = System.getProperty("os.name").lowercase()
        |        val osId = when {
        |            osName.contains("win") -> "windows"
        |            osName.contains("mac") || osName.contains("darwin") -> "macos"
        |            else -> "linux"
        |        }
        |
        |        val archName = System.getProperty("os.arch").lowercase()
        |        val archId = if (archName.contains("aarch64") || archName.contains("arm64")) {
        |            "$AARCH64_ID"
        |        } else {
        |            "$X86_64_ID"
        |        }
        |
        |        return osId + "-" + archId
        |    }
        |
        |    private fun fileName(name: String): String {
        |        val osName = System.getProperty("os.name").lowercase()
        |        return when {
        |            osName.contains("win") -> name + ".dll"
        |            osName.contains("mac") || osName.contains("darwin") -> "lib" + name + ".dylib"
        |            else -> "lib" + name + ".so"
        |        }
        |    }
        |
    """.trimMargin()
}
